/*
 * generated by Xtext
 */
package se.alanif.alan;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AlanStandaloneSetup extends AlanStandaloneSetupGenerated {

	public static void doSetup() {
		new AlanStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
