/*
 * generated by Xtext
 */
package se.alanif.alan;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlanRuntimeModule extends AbstractAlanRuntimeModule {
}
