/*
 * generated by Xtext
 */
package se.alanif.alan.validation;

/**
 * Custom Xtext validation rules (parse/model level). Real Alan-compiler
 * diagnostics are added by {@link AlanResourceValidator}.
 */
public class AlanValidator extends AbstractAlanValidator {
}
