/*
 * generated by Xtext
 */
package se.alanif.alan.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import se.alanif.alan.AlanRuntimeModule;
import se.alanif.alan.AlanStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AlanIdeSetup extends AlanStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlanRuntimeModule(), new AlanIdeModule()));
	}
	
}
