/*
 * generated by Xtext
 */
package se.alanif.alan.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class AlanScopeProvider extends AbstractAlanScopeProvider {

}
